[build]
builder = "nixpacks"
buildCommand = "bash build.sh"

[deploy]
startCommand = "python -m daily_ai_podcast.main"
restartPolicyType = "on_failure"

[phases.playwright]
dependsOn = ['install']
cmds = ['playwright install-deps']